---
title: "Tidycensus Introduction"
description: |
  How to connect to the US Census Bureau API simply done.
author:
  - name: Kiersten
    url: {}
date: 05-20-2021
output:
  distill::distill_article:
    self_contained: false
---

In my [previous post](https://kierrschill.github.io/posts/2021-05-19-second-try/), I mentioned how my senior project was centered around helping a local credit union understand the location in which they are opening a new branch. Part of this involves looking at the demographics of the population. In order to do this, I will be using [tidycensus](https://cran.r-project.org/web/packages/tidycensus/tidycensus.pdf), an R package that connects to the US Census Bureau's decennial census and five-year American Community APIs. The great thing about this package, is that it allows said census data to be returned in a usable [tidyverse](https://cran.r-project.org/web/packages/tidyverse/tidyverse.pdf) data frame. 

Some straight forward tutorials I found that I were useful are:

* [R Tutorial: Census data in R: An overview](https://www.youtube.com/watch?v=MDyGuWrBC-M) (time ~ 2:34 minutes)
* [R Tutorial: Basic tidycensus functionality](https://www.youtube.com/watch?v=i09Pc7orAYg) (time ~ 2:20 minutes)
* [R Tutorial: Searching for data with tidycensus](https://www.youtube.com/watch?v=dJRoubBvyq4) (time ~ 3:10 minutes)

To start, you first need to request an API key using your email address. This can be done at [https://api.census.gov/data/key_signup.html](https://api.census.gov/data/key_signup.html). After requesting, you should receive an email (I got mine after 5 minutes) that says something like:

> Hello!
>
> Thank you for your interest in the Census Data API. Your API key is [given API key here]. Please click here to activate your key. Save this email for future reference.
>
> Have Fun,
>
> The Census Bureau API Team

In the email that you initially recieve, make sure to click on the link to activate your given API key. After, you'll recieve another email stating that "Your key has been activated" and you can begin querying away.

To use my given API key in my R script, I used the following code:

```  {r API KEY}
# census_api_key('API KEY GOES HERE', overwrite = TRUE, install = TRUE)

# readRenviron("~/.Renviron")

# Sys.getenv("CENSUS_API_KEY")
```

And *Voilà*! You're all set to query to your hearts content!



